version: '3'
services:    
    mysql:
        image: mysql:5.6
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: "rootpassword"

    adminer:
        image: adminer
        ports:
            - 8080:8080
        depends_on:
            - mysql
    
    app:
        build: ./python
        volumes:
            - ./src:/app
        environment:
            MYSQL_HOST: "mysql"
            MYSQL_DB: "MeliChallenge"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "rootpassword"
            EMAIL_HOST: "imap.gmail.com"
            EMAIL_USER: "username@gmail.com"
            EMAIL_PASSWORD: "mailpassword"
        depends_on:
            - mysql